name: Build Windows EXE

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.3

      - name: Setup haxelib
        shell: cmd
        run: |
          haxelib setup %USERPROFILE%\haxelib

      - name: Install libraries
        shell: cmd
        run: |
          echo y | haxelib install lime
          echo y | haxelib install openfl
          echo y | haxelib install flixel
          echo y | haxelib install flixel-addons
          echo y | haxelib install flixel-ui
          echo y | haxelib install tjson
          echo y | haxelib install hxcpp

      - name: Lime / OpenFL setup
        shell: cmd
        run: |
          echo y | haxelib run lime setup windows
          echo y | haxelib run openfl setup

      - name: Build Windows EXE
        shell: cmd
        run: |
          haxelib run lime build windows -release

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: JogoSimples-Windows
          path: export/windows/bin
